server:
  port: 8071
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: admin
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka